name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # ou 'main' selon votre branche par défaut

permissions:
  contents: write  # Donne les permissions d'écriture sur le contenu du dépôt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Utilisez le répertoire racine